version: '2'
services:

  devpi:
    build:
      context: ./
      args:
        DEVPI_VERSION: 2.2.0
    image: muccg/devpi
    volumes:
      - ./data:/data
    ports:
      - 3141:3141
    environment:
      - DEVPI_PASSWORD=
    restart: always
